name: astridzhao_s_food_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.0.1
  intl: ^0.18.0
  bottom_navy_bar: ^6.0.0
  dot_navigation_bar: ^1.0.2
  flashy_tab_bar2: ^0.0.5
  botton_nav_bar: ^1.0.2
  openai_client: ^0.0.7
  language_picker: ^0.4.3
  dart_openai: ^3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Outfit
      fonts: 
        - asset: assets/fonts/OutfitSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
        - asset: assets/fonts/OutfitBold.ttf
          weight: 700
        - asset: assets/fonts/OutfitMedium.ttf
          weight: 500
        - asset: assets/fonts/OutfitLight.ttf
          weight: 300
    - family: Sora
      fonts: 
        - asset: assets/fonts/SoraSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
