name: astridzhao_s_food_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.2.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.0.1
  intl: ^0.18.0
  bottom_navy_bar: ^6.0.0
  flashy_tab_bar2: ^0.0.5
  botton_nav_bar: ^1.0.2
  openai_client: ^0.0.7
  language_picker: ^0.4.3
  dart_openai: ^3.0.0
  path: ^1.8.3
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  clipboard: ^0.1.3
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  provider: ^6.0.0
  sqlite3: ^2.3.0
  keyboard_actions: ^4.2.0
  test: ^1.24.9
  http: ^0.13.6
  shared_preferences: ^2.2.2
  auto_size_text: ^3.0.0
  gallery_saver: ^2.3.2
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.2.0
  dio: ^5.4.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flutter_bloc: ^8.1.3
  cloud_firestore: ^4.15.4
  purchases_flutter: ^6.21.0

dev_dependencies: 
  build_runner: ^2.4.8
  drift_dev: ^2.14.1
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Outfit
      fonts: 
        - asset: assets/fonts/OutfitSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
        - asset: assets/fonts/OutfitBold.ttf
          weight: 700
        - asset: assets/fonts/OutfitMedium.ttf
          weight: 500
        - asset: assets/fonts/OutfitLight.ttf
          weight: 300
    - family: Sora
      fonts: 
        - asset: assets/fonts/SoraSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
