// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwIq8pMX18V0k6DeCYKEJwG__cIIvKGi8',
    appId: '1:237872875039:web:cf8d589340a69399a2372a',
    messagingSenderId: '237872875039',
    projectId: 'ricebucket-f417d',
    authDomain: 'ricebucket-f417d.firebaseapp.com',
    storageBucket: 'ricebucket-f417d.appspot.com',
    measurementId: 'G-P1ZNBSWG6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJSBW-IKVTyPxCkWDPiHMZS1zAbtowVvc',
    appId: '1:237872875039:android:b7ab7a02e38d6b28a2372a',
    messagingSenderId: '237872875039',
    projectId: 'ricebucket-f417d',
    storageBucket: 'ricebucket-f417d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4i9a6-HRmIwUDcz4jX19CvNfbQmpCGV0',
    appId: '1:237872875039:ios:bed8cac5e7e4dfbca2372a',
    messagingSenderId: '237872875039',
    projectId: 'ricebucket-f417d',
    storageBucket: 'ricebucket-f417d.appspot.com',
    iosBundleId: 'com.example.BYOF.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4i9a6-HRmIwUDcz4jX19CvNfbQmpCGV0',
    appId: '1:237872875039:ios:a0d22cc37e7835eaa2372a',
    messagingSenderId: '237872875039',
    projectId: 'ricebucket-f417d',
    storageBucket: 'ricebucket-f417d.appspot.com',
    iosBundleId: 'com.example.foodapp.RunnerTests',
  );
}
